name: tagyourtaxi_driver
description: A new Flutter project.

publish_to: "none" 

version: 1.0.4+10

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  http: ^0.13.4
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_database: ^10.1.1
  firebase_messaging: ^14.4.1
  shared_preferences: ^2.0.12
  image_picker: ^0.8.4+4
  google_maps_flutter: ^2.1.12
  geolocator: ^9.0.1
  location: ^4.3.0
  audioplayers: ^0.20.1
  url_launcher: ^6.0.8
  flutter_local_notifications: ^12.0.4
  connectivity_plus: ^2.2.0
  contacts_service: ^0.6.3
  permission_handler: ^10.0.0
  share_plus: ^4.0.10+1
  flutterwave_standard: 1.0.2
  razorpay_flutter: ^1.3.2
  cashfree_pg: ^2.0.9+29
  uuid: ^3.0.6
  package_info_plus: ^4.0.2
  vector_math: ^2.1.1
  webview_flutter: ^3.0.4
  intl: ^0.17.0
  flutter_inappwebview: ^5.5.0+1
  path_provider: ^2.0.11
  heroicons: ^0.8.0
  hive: ^2.2.3
  cloud_firestore: ^4.8.2
  flutter_slidable: ^3.0.0
  flutter_sound: ^9.2.13
  audio_session: ^0.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/audio/
    - assets/icons/
    - assets/map_style.json
    - assets/maps_style.json
    - assets/map_style_black.json
